name: Publish

on:
  push:
    tags:
      - "crate-v*.*.*"

jobs:
  publish:
    name: Publish crate
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Update Rust stable
      run: rustup toolchain install stable
    # Restore cargo registry cache (source code artifacts only):
    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        restore-keys: |
          ${{ runner.os }}-cargo-registry-
    # Restore target cache
    - name: Restore third-party dependencies cache
      uses: actions/cache@v3
      with:
        path: target
        restore-keys: |
          ${{ runner.os }}-cargo-deps-
    # Verify if the crate is ready to be published:
    - name: Check crate is ready for publishing
      run: cargo package
    # Publish the crate to crates.io
    - name: Publish to crates.io
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cargo publish --token $CARGO_REGISTRY_TOKEN
